In [1]:
import requests
import pandas as pd
import datetime

## Getting the List of Available Symbols

In [33]:
symbols_url = 'http://127.0.0.1:8000/symbols'
list_of_symbols = requests.get(symbols_url).json()

In [34]:
list_of_symbols

{'1': 'سیمرغ',
 '2': 'وبرق',
 '3': 'دجابر',
 '4': 'وسنا',
 '5': 'وحافظ',
 '6': 'قلرست',
 '7': 'غویتا',
 '8': 'بفجر',
 '9': 'فاراک',
 '10': 'دتماد',
 '11': 'ساینا',
 '12': 'تپولا',
 '13': 'بالبر',
 '14': 'ختور',
 '15': 'آرمان',
 '16': 'پاسا',
 '17': 'خپارس',
 '18': 'فاذر',
 '19': 'چدن',
 '20': 'وسپه',
 '21': 'ثشاهد',
 '22': 'خموتور',
 '23': 'تاصیکو',
 '24': 'تکمبا',
 '25': 'غگز',
 '26': 'وسدید',
 '27': 'تاپیکو',
 '28': 'وهور',
 '29': 'غبشهر',
 '30': 'سبزوا',
 '31': 'قجام',
 '32': 'شصفها',
 '33': 'وتوس',
 '34': 'ولشرق',
 '35': 'خفنر',
 '36': 'وتجارت',
 '37': 'سقاین',
 '38': 'والبر',
 '39': 'کفپارس',
 '40': 'کشرق',
 '41': 'ختراک',
 '42': 'وثنو',
 '43': 'ثجوان',
 '44': 'کرمان',
 '45': 'ولملت',
 '46': 'کمرجان',
 '47': 'وساپا',
 '48': 'خدیزل',
 '49': 'تمحرکه',
 '50': 'وهنر',
 '51': 'فخوز',
 '52': 'سایرا',
 '53': 'پارسان',
 '54': 'نطرین',
 '55': 'ورنا',
 '56': 'فمراد',
 '57': 'وبیمه',
 '58': 'ددام',
 '59': 'سفار',
 '60': 'فلات',
 '61': 'لسرما',
 '62': 'شکلر',
 '63': 'تاپکیش',
 '64': 'فخاس',
 '65': 'وپاسار',
 '66': 'غمهرا',
 '67': 'قشیر',
 '68': 'شاوان',
 '69': 'وارس',
 '70': 'غپونه',
 '71': 'حخزر',
 '72': 'حکشتی',
 '73': 'شفارا',
 '74': 'لبوتان',
 '75': 'مداران',
 '76': 'غصینو',
 '77': 'خراسان',
 '78': 'چکارن',
 '79': 'وتوسم',
 '80': 'خکمک',
 '81': 'هجرت',
 '82': 'ومشان',
 '83': 'وثخوز',
 '84': 'شراز',
 '85': 'افق',
 '86': 'قزوین',
 '87': 'کی بی سی',
 '88': 'تکالا',
 '89': 'وبملت',
 '90': 'غشوکو',
 '91': 'شپنا',
 '92': 'آبین',
 '93': 'ختوقا',
 '94': 'پارتا',
 '95': 'غشهداب',
 '96': 'حفاری',
 '97': 'افرا',
 '98': 'قنیشا',
 '99': 'غپینو',
 '100': 'غشهد',
 '101': 'وشمال',
 '102': 'فجر',
 '103': 'زشریف',
 '104': 'ستران',
 '105': 'درهآور',
 '106': 'کسعدی',
 '107': 'شتران',
 '108': 'شپلی',
 '109': 'فروس',
 '110': 'ولصنم',
 '111': 'خکرمان',
 '112': 'سپرمی',
 '113': 'شپاکسا',
 '114': 'ثرود',
 '115': 'سفاسی',
 '116': 'دسینا',
 '117': 'شسم',
 '118': 'بپاس',
 '119': 'میهن',
 '120': 'سبجنو',
 '121': 'ولراز',
 '122': 'وآرین',
 '123': 'نوری',
 '124': 'شغدیر',
 '125': 'وآیند',
 '126': 'سدور',
 '127': 'فاما',
 '128': 'فرآور',
 '129': 'شپاس',
 '130': 'وآتوس',
 '131': 'ثاژن',
 '132': 'ولتجار',
 '133': 'خاهن',
 '134': 'وبوعلی',
 '135': 'تپمپی',
 '136': 'حاریا',
 '137': 'قاروم',
 '138': 'سصفها',
 '139': 'شفارس',
 '140': 'چافست',
 '141': 'فسا',
 '142': 'ساروم',
 '143': 'دماوند',
 '144': 'مارون',
 '145': 'شبندر',
 '146': 'کمینا',
 '147': 'پشاهن',
 '148': 'وآذر',
 '149': 'رمپنا',
 '150': 'چکاپا',
 '151': 'بشهاب',
 '152': 'وصندوق',
 '153': 'حتوکا',
 '154': 'دالبر',
 '155': 'وآوا',
 '156': 'کیمیا',
 '157': 'کویر',
 '158': 'ثشرق',
 '159': 'ثغرب',
 '160': 'شرنگی',
 '161': 'ثزاگرس',
 '162': 'شیران',
 '163': 'ثاخت',
 '164': 'ثاباد',
 '165': 'آینده',
 '166': 'وبشهر',
 '167': 'پکویر',
 '168': 'کماسه',
 '169': 'ثنام',
 '170': 'رتاپ',
 '171': 'ثاصفا',
 '172': 'فلامی',
 '173': 'وغدیر',
 '174': 'دارو',
 '175': 'پارس',
 '176': 'غفارس',
 '177': 'بجهرم',
 '178': 'لخانه',
 '179': 'وصنا',
 '180': 'کسرام',
 '181': 'وکادو',
 '182': 'گوهران',
 '183': 'دهدشت',
 '184': 'کلر',
 '185': 'سخواف',
 '186': 'دکیمی',
 '187': 'دفارا',
 '188': 'زماهان',
 '189': 'شستان',
 '190': 'وشهر',
 '191': 'خوساز',
 '192': 'قپیرا',
 '193': 'سصوفی',
 '194': 'ومعادن',
 '195': 'سلار',
 '196': 'دپارس',
 '197': 'اپرداز',
 '198': 'زقیام',
 '199': 'سمازن',
 '200': 'چکاوه',
 '201': 'ولانا',
 '202': 'بنو',
 '203': 'سباقر',
 '204': 'خاور',
 '205': 'شیراز',
 '206': 'بتک',
 '207': 'غچین',
 '208': 'فارس',
 '209': 'نکالا',
 '210': 'خصدرا',
 '211': 'غیوان',
 '212': 'کرماشا',
 '213': 'ورازی',
 '214': 'خمهر',
 '215': 'شاراک',
 '216': 'وثوق',
 '217': 'ولساپا',
 '218': 'وخارزم',
 '219': 'دانا',
 '220': 'خچرخش',
 '221': 'سکرد',
 '222': 'کابگن',
 '223': 'فسرب',
 '224': 'پتایر',
 '225': 'دسبحان',
 '226': 'پترول',
 '227': 'جهرم',
 '228': 'امید',
 '229': 'دابور',
 '230': 'ما',
 '231': 'خودکفا',
 '232': 'سهگمت',
 '233': 'حپترو',
 '234': 'شاملا',
 '235': 'خرینگ',
 '236': 'کلوند',
 '237': 'کگل',
 '238': 'سخوز',
 '239': 'فایرا',
 '240': 'لازما',
 '241': 'ارفع',
 '242': 'وسبحان',
 '243': 'فماک',
 '244': 'پاکشو',
 '245': 'شگل',
 '246': 'فروی',
 '247': 'وسرمد',
 '248': 'نبروج',
 '249': 'تکنو',
 '250': 'آسیا',
 '251': 'زدشت',
 '252': 'رکیش',
 '253': 'سدبیر',
 '254': 'فافزا',
 '255': 'کفرآور',
 '256': 'زمگسا',
 '257': 'خبهمن',
 '258': 'خعمرا',
 '259': 'سجام',
 '260': 'سغرب',
 '261': 'شوینده',
 '262': 'فملی',
 '263': 'سیدکو',
 '264': 'وتوکا',
 '265': 'دلر',
 '266': 'ممسنی',
 '267': 'غدشت',
 '268': 'بورس',
 '269': 'ثالوند',
 '270': 'داراب',
 '271': 'کگهر',
 '272': 'خاذین',
 '273': 'غدام',
 '274': 'بترانس',
 '275': 'دتهران\u200c',
 '276': 'قمرو',
 '277': 'شخارک',
 '278': 'فلوله',
 '279': 'کپارس',
 '280': 'ذوب',
 '281': 'وبهمن',
 '282': 'ثتوسا',
 '283': 'قاسم',
 '284': 'پدرخش',
 '285': 'رنیک',
 '286': 'ومهان',
 '287': 'پسهند',
 '288': 'ریشمک',
 '289': 'بساما',
 '290': 'سشمال',
 '291': 'خلنت',
 '292': 'غشاذر',
 '293': 'کگاز',
 '294': 'کقزوی',
 '295': 'داوه',
 '296': 'سدشت',
 '297': 'واتی',
 '298': 'کچاد',
 '299': 'شتوکا',
 '300': 'حسینا',
 '301': 'شدوص',
 '302': 'وتوصا',
 '303': 'سشرق',
 '304': 'بکاب',
 '305': 'کورز',
 '306': 'خودرو',
 '307': 'وپست',
 '308': 'خگستر',
 '309': 'اخابر',
 '310': 'قشرین',
 '311': 'وپسا',
 '312': 'فنرژی',
 '313': 'پردیس',
 '314': 'خشرق',
 '315': 'حریل',
 '316': 'دلقما',
 '317': 'دشیمی',
 '318': 'وجامی',
 '319': 'حفارس',
 '320': 'وحکمت',
 '321': 'وصنعت',
 '322': 'درازک',
 '323': 'کحافظ',
 '324': 'شکربن',
 '325': 'وسین',
 '326': 'فبیرا',
 '327': 'چنوپا',
 '328': 'کپشیر',
 '329': 'حبندر',
 '330': 'سرود',
 '331': 'سخاش',
 '332': 'شرانل',
 '333': 'بکهنوج',
 '334': 'ولبهمن',
 '335': 'فجوش',
 '336': 'فاسمین',
 '337': 'غگلپا',
 '338': 'کرازی',
 '339': 'گپارس',
 '340': 'غپآذر',
 '341': 'کمنگنز',
 '342': 'کهرام',
 '343': 'وکار',
 '344': 'داسوه',
 '345': 'شتهران',
 '346': 'مرقام',
 '347': 'شسپا',
 '348': 'وایرا',
 '349': 'ونیکی',
 '350': 'فاهواز',
 '351': 'سبهان',
 '352': 'فولاژ',
 '353': 'برکت',
 '354': 'کالا',
 '355': 'ثعتما',
 '356': 'سمتاز',
 '357': 'های وب',
 '358': 'شمواد',
 '359': 'پکرمان',
 '360': 'شفا',
 '361': 'وآفری',
 '362': 'بالاس',
 '363': 'دتوزیع',
 '364': 'کسرا',
 '365': 'قشکر',
 '366': 'خریخت',
 '367': 'ثنظام',
 '368': 'لکما',
 '369': 'تکشا',
 '370': 'واعتبار',
 '371': 'قهکمت',
 '372': 'بموتو',
 '373': 'واحیا',
 '374': 'تنوین',
 '375': 'تفیرو',
 '376': 'وبصادر',
 '377': 'ثباغ',
 '378': 'سنیر',
 '379': 'پلاسک',
 '380': 'شسینا',
 '381': 'وسالت',
 '382': 'وخاور',
 '383': 'سهرمز',
 '384': 'زشگزا',
 '385': 'تبرک',
 '386': 'زفکا',
 '387': 'کوثر',
 '388': 'تابا',
 '389': 'دکوثر',
 '390': 'شلرد',
 '391': 'وملی',
 '392': 'ساراب',
 '393': 'تکنار',
 '394': 'زبینا',
 '395': 'دسانکو',
 '396': 'لخزر',
 '397': 'تشتاد',
 '398': 'پلوله',
 '399': 'شپدیس',
 '400': 'ومعلم',
 '401': 'اعتلا',
 '402': 'سپ',
 '403': 'نوین',
 '404': 'همراه',
 '405': 'اتکای',
 '406': 'معیار ',
 '407': 'نمرینو',
 '408': 'غدیس',
 '409': 'خزر',
 '410': 'وامید',
 '411': 'شگامرن',
 '412': 'بمیلا',
 '413': 'مادیرا',
 '414': 'غگلستا',
 '415': 'سفانو',
 '416': 'فولای',
 '417': 'ثمسکن',
 '418': 'کنور',
 '419': 'کبافق',
 '420': 'فبستم',
 '421': 'شبریز',
 '422': 'دشیری',
 '423': 'بخاور',
 '424': 'دبالک',
 '425': 'دفرا',
 '426': 'وایران',
 '427': 'فسدید',
 '428': 'توسعه',
 '429': 'قصفها',
 '430': 'فنوال',
 '431': 'وبانک',
 '432': 'کدما',
 '433': 'فجام',
 '434': 'دروز',
 '435': 'کیسون',
 '436': 'فباهنر',
 '437': 'گکیش',
 '438': 'لابسا',
 '439': 'غسالم',
 '440': 'بایکا',
 '441': 'ثپردیس',
 '442': 'ولغدر',
 '443': 'فنفت',
 '444': 'بنیرو',
 '445': 'بزاگرس',
 '446': 'سیستم',
 '447': 'قشهد',
 '448': 'خمحور',
 '449': 'هرمز',
 '450': 'وگستر',
 '451': 'کاذر',
 '452': 'ثنور',
 '453': 'غشصفا',
 '454': 'تپکو',
 '455': 'فن آوا',
 '456': 'سکرما',
 '457': 'کازرو',
 '458': 'سیلام',
 '459': 'ونیرو',
 '460': 'دقاضی',
 '461': 'شپارس',
 '462': 'تیپیکو',
 '463': 'شتولی',
 '464': 'قرن',
 '465': 'سخزر',
 '466': 'خساپا',
 '467': 'کاما',
 '468': 'وتعاون',
 '469': 'سرچشمه',
 '470': 'خمحرکه',
 '471': 'ساربیل',
 '472': 'کفرا',
 '473': 'وگردش',
 '474': 'توریل',
 '475': 'بهپاک',
 '476': 'فسپا',
 '477': 'شکبیر',
 '478': 'خفناور',
 '479': 'لپیام',
 '480': 'لوتوس',
 '481': 'دتولید',
 '482': 'کترام',
 '483': 'فسازان',
 '484': 'فولاد',
 '485': 'میدکو',
 '486': 'چفیبر',
 '487': 'کساپا',
 '488': 'کصدف',
 '489': 'کباده',
 '490': 'وزمین',
 '491': 'جم پیلن',
 '492': 'نیرو',
 '493': 'کتوکا',
 '494': 'وملت',
 '495': 'کاوه',
 '496': 'بمپنا',
 '497': 'حتاید',
 '498': 'شجم',
 '499': 'زگلدشت',
 '500': 'ثامان',
 '501': 'کپرور',
 '502': 'فوکا',
 '503': 'دکپسول',
 '504': 'اوان',
 '505': 'واحصا',
 '506': 'غبهنوش',
 '507': 'وپخش',
 '508': 'شفن',
 '509': 'سمگا',
 '510': 'خکار',
 '511': 'دعبید',
 '512': 'کروی',
 '513': 'ونفت',
 '514': 'آپ',
 '515': 'آریان',
 '516': 'وتوشه',
 '517': 'دامین',
 '518': 'ثقزوی',
 '519': 'وسینا',
 '520': 'پلاست',
 '521': 'ونوین',
 '522': 'خفولا',
 '523': 'کاسپین',
 '524': 'دحاوی',
 '525': 'دسبحا',
 '526': 'رانفور',
 '527': 'غنیلی',
 '528': 'خنصیر',
 '529': 'غگرجی',
 '530': 'رتکو',
 '531': 'شپترو',
 '532': 'فپنتا',
 '533': 'ثعمرا',
 '534': 'زنجان',
 '535': 'غبهار',
 '536': 'سفارس',
 '537': 'وملل',
 '538': 'فزرین',
 '539': 'پخش',
 '540': 'کطبس',
 '541': 'مبین',
 '542': 'وپترو',
 '543': 'زپارس',
 '544': 'تلیسه',
 '545': 'سپاها',
 '546': 'شزنگ',
 '547': 'ثفارس',
 '548': 'مفاخر',
 '549': 'دیران',
 '550': 'زاگرس',
 '551': 'غاذر',
 '552': 'حپارسا',
 '553': 'ودی',
 '554': 'ساذری',
 '555': 'سامان',
 '556': 'سکارون',
 '557': 'اتکام',
 '558': 'قنقش',
 '559': 'لپارس',
 '560': 'شبصیر',
 '561': 'خپویش',
 '562': 'پرداخت',
 '563': 'شنفت',
 '564': 'البرز',
 '565': 'پارسیان',
 '566': 'کایتا',
 '567': 'شبهرن',
 '568': 'خزامیا',
 '569': 'غالبر',
 '570': 'جم',
 '571': 'کهمدا',
 '572': 'حآسا',
 '573': 'تایرا',
 '574': 'وساخت',
 '575': 'قچار',
 '576': 'بکام',
 '577': 'وپارس',
 '578': 'خکاوه',
 '579': 'فالوم',
 '580': 'ثتران',
 '581': 'گکوثر',
 '582': 'ثنوسا',
 '583': 'کخاک'}

## Recieving Detailed Information (With Declaration of the Duration)

In [23]:
url = symbols_url + '/' + list_of_symbols['1']
headers = {"starting": "2019-06-26", 'ending': '2020-06-10'}
r = requests.get(url, headers=headers)

In [24]:
detailed_symbol = r.json()

### Creating a DataFrame from the JSON Response

In [25]:
df = pd.read_json(detailed_symbol)

In [26]:
df

,date,open,high,low,adjClose,value,volume,count,close
0,2019-06-26,5596,5596,5596,5583,2772913132,495517,1785,5596
1,2019-06-30,5862,5862,5862,5862,3626831124,618702,2215,5862
2,2019-07-01,6155,6155,6155,6155,5236409335,850757,3014,6155
3,2019-07-02,6462,6462,6462,6462,4237191558,655709,2343,6462
4,2019-07-03,6785,6785,6785,6785,5944155305,876073,3657,6785
...,...,...,...,...,...,...,...,...,...
221,2020-06-06,32300,32600,31500,32474,266894301679,8218635,3750,32600
222,2020-06-07,33499,34097,32700,33635,389329768591,11575257,6413,32951
223,2020-06-08,31718,35056,31559,32185,398105041283,12369400,5898,31718
224,2020-06-09,31800,32890,31027,31725,377487935354,11898826,4949,31350
225,2020-06-10,33311,33311,33311,33311,163379828791,4904681,1647,33311

## Recieving Detailed Information (No Duration Declared --> Receving the Whole)

In [29]:
url = symbols_url + '/' + list_of_symbols['1']
rr = requests.get(url)

In [30]:
detailed_symbol = rr.json()

In [31]:
df = pd.read_json(detailed_symbol)

In [32]:
df

,date,open,high,low,adjClose,value,volume,count,close
0,2019-06-23,5100,5100,5100,5100,662993818800,129998788,433736,5100
1,2019-06-24,5355,5355,5355,5170,761545260,142212,556,5355
2,2019-06-25,5428,5428,5428,5330,1750242316,322447,1215,5428
3,2019-06-26,5596,5596,5596,5583,2772913132,495517,1785,5596
4,2019-06-30,5862,5862,5862,5862,3626831124,618702,2215,5862
...,...,...,...,...,...,...,...,...,...
228,2020-06-10,33311,33311,33311,33311,163379828791,4904681,1647,33311
229,2020-06-13,34970,34970,34970,34970,132395300960,3785968,1034,34970
230,2020-06-14,36710,36710,34980,36450,1153332042320,31643806,11553,36710
231,2020-06-15,36900,37900,34630,35960,582288185130,16192090,9332,35280
232,2020-06-16,35940,37580,34170,36110,582088869650,16120330,8551,36970